import React, { useState, useEffect, useCallback } from 'react';
import { Repository, User } from '../types';
import { useToast } from './ToastContext';
import { DocumentPlusIcon, SpinnerIcon, ErrorIcon, SettingsIcon, GithubIcon, BrainCircuitIcon } from './icons';
import { generateReadmeFromContext, isApiKeySet } from '../services/geminiService';
import { createOrUpdateReadmeAndPR, getRepoContextForReadme, parseGitHubUrl } from '../services/githubService';
import CodeMirror from '@uiw/react-codemirror';
import { atomone } from '@uiw/codemirror-theme-atomone';
import { useTheme } from './ThemeContext';
import { javascript } from '@codemirror/lang-javascript'; // Using JS for Markdown highlighting as a fallback
import { motion } from 'framer-motion';

interface READMEGeneratorProps {
    repos: Repository[];
    user: User | null;
    onNavigateToSettings: () => void;
}

type GeneratorState = 'idle' | 'analyzing' | 'generating' | 'done' | 'creating_pr';

const templateOptions = [
    { id: 'auto', name: '🤖 Auto-Select Style' },
    { id: 'minimalist', name: 'Minimalist' },
    { id: 'startup', name: 'Startup' },
    { id: 'open-source', name: 'Open Source' },
    { id: 'enterprise', name: 'Enterprise' },
    { id: 'docs', name: 'Documentation' },
];

const READMEGenerator: React.FC<READMEGeneratorProps> = ({ repos, user, onNavigateToSettings }) => {
    const { addToast } = useToast();
    const { theme } = useTheme();
    const [selectedRepoFullName, setSelectedRepoFullName] = useState<string>('');
    const [state, setState] = useState<GeneratorState>('idle');
    const [apiKeyMissing, setApiKeyMissing] = useState(false);
    const [generatedReadme, setGeneratedReadme] = useState('');
    const [selectedTemplate, setSelectedTemplate] = useState('auto');

    useEffect(() => {
        if (repos.length > 0 && !selectedRepoFullName) {
            setSelectedRepoFullName(repos[0].full_name);
        }
    }, [repos, selectedRepoFullName]);

    useEffect(() => {
        setApiKeyMissing(!isApiKeySet());
    }, []);

    const handleGenerate = async () => {
        if (!selectedRepoFullName) {
            addToast('Please select a repository.', 'warning');
            return;
        }
        
        setState('analyzing');
        setGeneratedReadme('');
        addToast('Starting deep repository analysis...', 'info');

        try {
            const context = await getRepoContextForReadme(selectedRepoFullName);
            
            setState('generating');
            addToast('Analysis complete. Generating README with AI...', 'info');

            const content = await generateReadmeFromContext(context, selectedTemplate);
            setGeneratedReadme(content);
            setState('done');
            addToast('README generated successfully!', 'success');

        } catch (e: any) {
            addToast(e.message, 'error');
            setState('idle');
        }
    };

    const handleCreatePR = async () => {
        if (!generatedReadme) {
            addToast('Please generate a README before creating a PR.', 'warning');
            return;
        }
        setState('creating_pr');
        try {
            const parsed = parseGitHubUrl(`https://github.com/${selectedRepoFullName}`);
            if (!parsed) throw new Error("Invalid repo name.");
            
            const prUrl = await createOrUpdateReadmeAndPR(
                parsed.owner, parsed.repo, generatedReadme,
                "docs: Add/Update README.md with Sentinel AI",
                "This PR was generated by Sentinel AI's autonomous README Generator."
            );
            
            addToast(<span>PR created successfully! <a href={prUrl} target="_blank" rel="noopener noreferrer" className="underline">View Pull Request</a></span>, 'success');
            setState('idle');
            setGeneratedReadme('');

        } catch (e: any) {
            addToast(e.message, 'error');
            setState('done');
        }
    };

    if (apiKeyMissing || !user?.github) {
        return (
            <div className="h-full w-full flex items-center justify-center p-4 glass-effect rounded-lg">
                <div className="text-center">
                     <ErrorIcon className="w-12 h-12 text-yellow-500 mb-4 mx-auto" />
                     <h3 className="text-lg font-bold">Setup Required</h3>
                     <p className="mt-2 text-medium-dark-text max-w-sm">Please set your Gemini API Key and connect to GitHub in Settings to use this feature.</p>
                     <button onClick={onNavigateToSettings} className="mt-6 btn-primary flex items-center mx-auto">
                        <SettingsIcon className="w-5 h-5 mr-2" /> Go to Settings
                    </button>
                </div>
            </div>
        );
    }
    
    const isLoading = state === 'analyzing' || state === 'generating' || state === 'creating_pr';
    
    const getButtonContent = () => {
        switch(state) {
            case 'idle':
                return <><BrainCircuitIcon className="w-5 h-5 mr-2" /> Generate README</>;
            case 'analyzing':
                return <><SpinnerIcon className="w-5 h-5 mr-2" /> Analyzing Repo...</>;
            case 'generating':
                return <><SpinnerIcon className="w-5 h-5 mr-2" /> Generating with AI...</>;
            case 'done':
                return <><GithubIcon className="w-5 h-5 mr-2" /> Create PR with README</>;
            case 'creating_pr':
                 return <><SpinnerIcon className="w-5 h-5 mr-2" /> Creating PR...</>;
        }
    };

    return (
        <div className="h-full w-full flex flex-col space-y-4 animate-fade-in-up">
            <div className="flex-shrink-0 flex flex-col md:flex-row md:items-center md:justify-between">
                <div className="flex items-center space-x-3">
                    <DocumentPlusIcon className="w-8 h-8 text-brand-purple" />
                    <div>
                        <h1 className="text-3xl font-bold font-heading">Autonomous README Generator</h1>
                        <p className="mt-1 text-medium-dark-text">Select a repo, click generate. The AI does the rest.</p>
                    </div>
                </div>
            </div>

            <div className="flex-grow grid grid-cols-1 gap-4 min-h-0">
                <div className="glass-effect rounded-lg p-4 flex flex-col">
                    <div className="flex-shrink-0 flex flex-col sm:flex-row sm:items-center sm:justify-between mb-4">
                        <h2 className="text-lg font-bold font-heading">Live Preview</h2>
                        <div className="flex items-center space-x-3 mt-3 sm:mt-0">
                             {repos.length > 0 && (
                                <select value={selectedRepoFullName} onChange={e => setSelectedRepoFullName(e.target.value)} disabled={isLoading} className="w-full sm:w-60 bg-light-primary dark:bg-dark-primary p-2 rounded-md text-sm border border-gray-200 dark:border-white/10">
                                    {repos.map(repo => <option key={repo.id} value={repo.full_name}>{repo.full_name}</option>)}
                                </select>
                            )}
                            <select
                                value={selectedTemplate}
                                onChange={e => setSelectedTemplate(e.target.value)}
                                disabled={isLoading}
                                className="w-full sm:w-60 bg-light-primary dark:bg-dark-primary p-2 rounded-md text-sm border border-gray-200 dark:border-white/10"
                            >
                                {templateOptions.map(opt => <option key={opt.id} value={opt.id}>{opt.name}</option>)}
                            </select>
                             <motion.button 
                                onClick={state === 'done' ? handleCreatePR : handleGenerate} 
                                disabled={isLoading || !selectedRepoFullName} 
                                className="btn-primary py-2 px-4 disabled:opacity-50 flex items-center justify-center w-60"
                                key={state === 'done' ? 'pr' : 'gen'}
                             >
                                {getButtonContent()}
                            </motion.button>
                        </div>
                    </div>
                    <div className="flex-grow min-h-0 border-t border-gray-200 dark:border-white/10 pt-2">
                        {isLoading && state !== 'creating_pr' ? (
                            <div className="h-full flex items-center justify-center text-center">
                                <div>
                                    <SpinnerIcon className="w-10 h-10 text-brand-purple mx-auto" />
                                    <p className="mt-3 font-semibold">{state === 'analyzing' ? 'Performing deep analysis...' : 'Generating README with AI...'}</p>
                                    <p className="text-sm text-medium-dark-text dark:text-medium-text">This may take a few moments.</p>
                                </div>
                            </div>
                        ) : (
                            <CodeMirror 
                                value={generatedReadme}
                                onChange={(value) => setGeneratedReadme(value)}
                                extensions={[javascript({ jsx: true })]} // Using JS for basic Markdown highlighting
                                theme={theme === 'dark' ? atomone : 'light'}
                                readOnly={isLoading}
                            />
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default READMEGenerator;