import React, { useState, useEffect } from 'react';
import { Repository, User } from '../types';
import { useToast } from './ToastContext';
import { DocumentPlusIcon, SpinnerIcon, ErrorIcon, SettingsIcon, GithubIcon, BrainCircuitIcon, EyeIcon, CodeIcon, ChevronDownIcon } from './icons';
import { generateReadmeFromContext, isApiKeySet } from '../services/geminiService';
import { createOrUpdateReadmeAndPR, getRepoContextForReadme, parseGitHubUrl } from '../services/githubService';
import CodeMirror from '@uiw/react-codemirror';
import { atomone } from '@uiw/codemirror-theme-atomone';
import { useTheme } from './ThemeContext';
import { javascript } from '@codemirror/lang-javascript';
import { motion, AnimatePresence } from 'framer-motion';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import Dropdown from './Dropdown';

interface READMEGeneratorProps {
    repos: Repository[];
    user: User | null;
    onNavigateToSettings: () => void;
}

type GeneratorState = 'idle' | 'analyzing' | 'generating' | 'done' | 'creating_pr';
type ViewMode = 'edit' | 'preview' | 'split';

const templateOptions = [
    { id: 'auto', name: '🤖 Auto-Select Style' },
    { id: 'minimalist', name: 'Minimalist' },
    { id: 'startup', name: 'Startup' },
    { id: 'open-source', name: 'Open Source' },
    { id: 'enterprise', name: 'Enterprise' },
    { id: 'docs', name: 'Documentation' },
];

const READMEGenerator: React.FC<READMEGeneratorProps> = ({ repos, user, onNavigateToSettings }) => {
    const { addToast } = useToast();
    const { theme } = useTheme();
    const [selectedRepoFullName, setSelectedRepoFullName] = useState<string>('');
    const [state, setState] = useState<GeneratorState>('idle');
    const [apiKeyMissing, setApiKeyMissing] = useState(false);
    const [generatedReadme, setGeneratedReadme] = useState('');
    const [selectedTemplate, setSelectedTemplate] = useState('auto');
    const [viewMode, setViewMode] = useState<ViewMode>('split');

    useEffect(() => {
        if (repos.length > 0 && !selectedRepoFullName) {
            setSelectedRepoFullName(repos[0].full_name);
        }
    }, [repos, selectedRepoFullName]);

    useEffect(() => {
        setApiKeyMissing(!isApiKeySet());
    }, []);

    const handleGenerate = async () => {
        if (!selectedRepoFullName) {
            addToast('Please select a repository.', 'warning');
            return;
        }

        setState('analyzing');
        setGeneratedReadme('');
        addToast('Starting deep repository analysis...', 'info');

        try {
            const context = await getRepoContextForReadme(selectedRepoFullName);

            setState('generating');
            addToast('Analysis complete. Generating README with AI...', 'info');

            const content = await generateReadmeFromContext(context, selectedTemplate);
            setGeneratedReadme(content);
            setState('done');
            addToast('README generated successfully!', 'success');

        } catch (e: any) {
            addToast(e.message, 'error');
            setState('idle');
        }
    };

    const handleCreatePR = async () => {
        if (!generatedReadme) {
            addToast('Please generate a README before creating a PR.', 'warning');
            return;
        }
        setState('creating_pr');
        try {
            const parsed = parseGitHubUrl(`https://github.com/${selectedRepoFullName}`);
            if (!parsed) throw new Error("Invalid repo name.");

            const prUrl = await createOrUpdateReadmeAndPR(
                parsed.owner, parsed.repo, generatedReadme,
                "docs: Add/Update README.md with Sentinel AI",
                "This PR was generated by Sentinel AI's autonomous README Generator."
            );

            addToast(<span>PR created successfully! <a href={prUrl} target="_blank" rel="noopener noreferrer" className="underline">View Pull Request</a></span>, 'success');
            setState('idle');
            setGeneratedReadme('');

        } catch (e: any) {
            addToast(e.message, 'error');
            setState('done');
        }
    };

    if (apiKeyMissing || !user?.github) {
        return (
            <div className="h-full w-full flex items-center justify-center p-4">
                <div className="text-center bg-black/40 backdrop-blur-xl border border-white/10 p-10 rounded-3xl shadow-2xl max-w-md">
                    <ErrorIcon className="w-16 h-16 text-red-500 mb-6 mx-auto animate-pulse" />
                    <h3 className="text-2xl font-bold text-white mb-2 font-heading">Access Denied</h3>
                    <p className="mt-2 text-gray-400">Security protocols require API configuration and GitHub authentication.</p>
                    <button onClick={onNavigateToSettings} className="mt-8 px-8 py-3 bg-white text-black font-bold rounded-full hover:scale-105 transition-transform flex items-center mx-auto">
                        <SettingsIcon className="w-5 h-5 mr-2" /> Configure System
                    </button>
                </div>
            </div>
        );
    }

    const isLoading = state === 'analyzing' || state === 'generating' || state === 'creating_pr';

    return (
    return (
        <div className="h-full w-full flex flex-col space-y-6 animate-fade-in-up p-6">
            {/* Header Section */}
            <div className="flex-shrink-0 flex flex-col md:flex-row md:items-center md:justify-between bg-black/40 backdrop-blur-xl border border-white/10 p-6 rounded-3xl relative z-20">
                <div className="flex items-center space-x-4">
                    <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-purple-500/20 to-blue-500/20 border border-white/10 flex items-center justify-center">
                        <DocumentPlusIcon className="w-6 h-6 text-white" />
                    </div>
                    <div>
                        <h1 className="text-2xl font-bold font-heading text-white">README Generator</h1>
                        <p className="text-gray-400 text-sm">Autonomous documentation architect</p>
                    </div>
                </div>

                <div className="flex items-center space-x-3 mt-4 md:mt-0">
                    {repos.length > 0 && (
                        <Dropdown
                            trigger={
                                <button className="flex items-center justify-between w-64 bg-black/50 border border-white/10 text-white px-4 py-2.5 rounded-xl hover:border-purple-500/50 transition-colors text-sm">
                                    <span className="truncate">{selectedRepoFullName || 'Select Repository'}</span>
                                    <ChevronDownIcon className="w-4 h-4 text-gray-500 ml-2" />
                                </button>
                            }
                            items={repos.map(repo => ({
                                id: repo.full_name,
                                label: repo.full_name,
                                onClick: () => setSelectedRepoFullName(repo.full_name)
                            }))}
                            width="w-64"
                        />
                    )}

                    <Dropdown
                        trigger={
                            <button className="flex items-center justify-between w-48 bg-black/50 border border-white/10 text-white px-4 py-2.5 rounded-xl hover:border-purple-500/50 transition-colors text-sm">
                                <span className="truncate">{templateOptions.find(t => t.id === selectedTemplate)?.name || 'Select Template'}</span>
                                <ChevronDownIcon className="w-4 h-4 text-gray-500 ml-2" />
                            </button>
                        }
                        items={templateOptions.map(opt => ({
                            id: opt.id,
                            label: opt.name,
                            onClick: () => setSelectedTemplate(opt.id)
                        }))}
                        width="w-48"
                    />

                    <motion.button
                        whileHover={{ scale: 1.02 }}
                        whileTap={{ scale: 0.98 }}
                        onClick={state === 'done' ? handleCreatePR : handleGenerate}
                        disabled={isLoading || !selectedRepoFullName}
                        className={`
                            relative overflow-hidden px-6 py-2.5 rounded-xl font-bold text-sm flex items-center justify-center min-w-[160px] transition-all
                            ${isLoading ? 'bg-white/5 text-gray-500 cursor-not-allowed' : 'bg-white text-black hover:shadow-[0_0_20px_rgba(255,255,255,0.3)]'}
                        `}
                    >
                        {isLoading ? (
                            <><SpinnerIcon className="w-4 h-4 mr-2 animate-spin" /> Processing...</>
                        ) : state === 'done' ? (
                            <><GithubIcon className="w-4 h-4 mr-2" /> Create PR</>
                        ) : (
                            <><BrainCircuitIcon className="w-4 h-4 mr-2" /> Generate</>
                        )}
                    </motion.button>
                </div>
            </div>

            {/* Main Content Area */}
            <div className="flex-grow min-h-0 grid grid-rows-[auto_1fr] gap-4 relative z-10">
                {/* Toolbar */}
                <div className="flex items-center justify-between px-2">
                    <div className="flex bg-black/40 backdrop-blur-xl border border-white/10 rounded-lg p-1">
                        <button
                            onClick={() => setViewMode('edit')}
                            className={`px-3 py-1.5 rounded-md text-xs font-medium transition-all ${viewMode === 'edit' ? 'bg-white/10 text-white' : 'text-gray-500 hover:text-gray-300'}`}
                        >
                            <CodeIcon className="w-3.5 h-3.5 inline mr-1.5" /> Editor
                        </button>
                        <button
                            onClick={() => setViewMode('split')}
                            className={`px-3 py-1.5 rounded-md text-xs font-medium transition-all ${viewMode === 'split' ? 'bg-white/10 text-white' : 'text-gray-500 hover:text-gray-300'} hidden md:block`}
                        >
                            <span className="flex items-center"><span className="w-3.5 h-3.5 border-r border-current mr-1.5 opacity-50"></span> Split</span>
                        </button>
                        <button
                            onClick={() => setViewMode('preview')}
                            className={`px-3 py-1.5 rounded-md text-xs font-medium transition-all ${viewMode === 'preview' ? 'bg-white/10 text-white' : 'text-gray-500 hover:text-gray-300'}`}
                        >
                            <EyeIcon className="w-3.5 h-3.5 inline mr-1.5" /> Preview
                        </button>
                    </div>
                    {generatedReadme && (
                        <div className="text-xs text-gray-500 font-mono">
                            {generatedReadme.length} chars • {generatedReadme.split('\n').length} lines
                        </div>
                    )}
                </div>

                {/* Editor/Preview Container */}
                <div className="relative flex-grow min-h-0 bg-black/40 backdrop-blur-xl border border-white/10 rounded-3xl overflow-hidden shadow-2xl">
                    {isLoading && state !== 'creating_pr' ? (
                        <div className="absolute inset-0 z-50 flex flex-col items-center justify-center bg-black/60 backdrop-blur-sm">
                            <div className="relative">
                                <div className="w-20 h-20 border-4 border-white/10 border-t-white rounded-full animate-spin"></div>
                                <div className="absolute inset-0 flex items-center justify-center">
                                    <BrainCircuitIcon className="w-8 h-8 text-white/50 animate-pulse" />
                                </div>
                            </div>
                            <p className="mt-6 text-lg font-bold text-white tracking-wide animate-pulse">
                                {state === 'analyzing' ? 'ANALYZING REPOSITORY STRUCTURE' : 'SYNTHESIZING DOCUMENTATION'}
                            </p>
                            <p className="text-sm text-gray-500 mt-2 font-mono">This may take a moment...</p>
                        </div>
                    ) : null}

                    <div className={`h-full w-full grid ${viewMode === 'split' ? 'grid-cols-2 divide-x divide-white/10' : 'grid-cols-1'}`}>
                        {/* Editor Pane */}
                        {(viewMode === 'edit' || viewMode === 'split') && (
                            <div className="h-full overflow-hidden flex flex-col">
                                <div className="bg-white/5 px-4 py-2 border-b border-white/5 text-xs font-mono text-gray-500 uppercase tracking-wider flex justify-between items-center">
                                    <span>Markdown Source</span>
                                </div>
                                <div className="flex-grow overflow-auto custom-scrollbar">
                                    <CodeMirror
                                        value={generatedReadme}
                                        onChange={(value) => setGeneratedReadme(value)}
                                        extensions={[javascript({ jsx: true })]}
                                        theme={atomone}
                                        className="h-full text-sm"
                                        height="100%"
                                        basicSetup={{
                                            lineNumbers: true,
                                            highlightActiveLineGutter: true,
                                            highlightSpecialChars: true,
                                            history: true,
                                            foldGutter: true,
                                            drawSelection: true,
                                            dropCursor: true,
                                            allowMultipleSelections: true,
                                            indentOnInput: true,
                                            syntaxHighlighting: true,
                                            bracketMatching: true,
                                            closeBrackets: true,
                                            autocompletion: true,
                                            rectangularSelection: true,
                                            crosshairCursor: true,
                                            highlightActiveLine: true,
                                            highlightSelectionMatches: true,
                                            closeBracketsKeymap: true,
                                            defaultKeymap: true,
                                            searchKeymap: true,
                                            historyKeymap: true,
                                            foldKeymap: true,
                                            completionKeymap: true,
                                            lintKeymap: true,
                                        }}
                                    />
                                </div>
                            </div>
                        )}

                        {/* Preview Pane */}
                        {(viewMode === 'preview' || viewMode === 'split') && (
                            <div className="h-full overflow-hidden flex flex-col bg-[#0d1117]">
                                <div className="bg-white/5 px-4 py-2 border-b border-white/5 text-xs font-mono text-gray-500 uppercase tracking-wider flex justify-between items-center">
                                    <span>Live Preview</span>
                                </div>
                                <div className="flex-grow overflow-auto p-8 custom-scrollbar prose prose-invert max-w-none prose-headings:font-heading prose-a:text-blue-400 prose-pre:bg-[#161b22] prose-pre:border prose-pre:border-white/10 prose-blockquote:border-l-4 prose-blockquote:border-white/20 prose-blockquote:bg-white/5 prose-blockquote:px-4 prose-blockquote:py-1 prose-code:text-blue-300 prose-code:bg-white/5 prose-code:px-1 prose-code:rounded prose-code:before:content-none prose-code:after:content-none">
                                    {generatedReadme ? (
                                        <ReactMarkdown remarkPlugins={[remarkGfm]}>
                                            {generatedReadme}
                                        </ReactMarkdown>
                                    ) : (
                                        <div className="h-full flex flex-col items-center justify-center text-gray-600 opacity-50">
                                            <EyeIcon className="w-12 h-12 mb-4" />
                                            <p>Preview will appear here</p>
                                        </div>
                                    )}
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default READMEGenerator;